spring:
  datasource:
    url: ${POSTGRESQL_URL_DEV:}
    username: ${POSTGRESQL_USERNAME_DEV:postgres}
    password: ${POSTGRESQL_PASSWORD_DEV:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

logging:
  level:
    root: WARN
    br.com.resenhasociocultural: DEBUG