spring:
  application:
    name: resenha-sociocultural-api
  jwt:
    rsa-private-key:
      json: ${RSA_PRIVATE_KEY_JSON:}
  output:
    ansi:
      enabled: ALWAYS

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /openapi.yaml
    oauth:
      use-pkce-with-authorization-code-grant: true
