spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password: user
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration