spring:
  datasource:
    url: ${POSTGRESQL_URL_DEV:}
    username: ${POSTGRESQL_USERNAME:admin}
    password: ${POSTGRESQL_PASSWORD:admin}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

openapi-config:
  server-url: http://localhost:8080
  auth-url: http://localhost:8080/oauth2/authorize
  token-url: http://localhost:8080/oauth2/token
  server-description: Some Development Server

app:
  database:
    seed-on-startup: true

logging:
  level:
    root: WARN
    br.com.resenhasociocultural: DEBUG